# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node JS
      uses: actions/setup-node@v1.4.1
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ./web/nadestack-frontend/node_modules/
        key: ${{ runner.os }}-node_modules
       
    - name: Build JS files
      working-directory: ./web/nadestack-frontend/
      env: 
        NODE_ENV: production
      run: | 
        yarn install
        yarn build
        
    - name: add artifacts to git
      run: |
        rm -rf .git/
        git init
        git add .
        git add --force web/nadestack-frontend/build/
        git status
        git config --global user.email "ci@githubactions"
        git config --global user.name "CI"
        git commit -m "build"
        
    - name: Dokku deploy
      uses: th0mas/dokku-github-action@4.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        HOST: ${{ secrets.DOKKU_IP }}
        PROJECT: nadestack
        
      
      
      
